name: Generate and commit prefixes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 04 * * FRI"
  workflow_dispatch:

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up SOCKS5 proxy with Dante
      run: |
        sudo apt-get update
        sudo apt-get install -y dante-server
        sudo sh -c 'echo "internal: ${{ secrets.SOCKS_ADDRESS }} port = ${{ secrets.SOCKS_PORT }}" >> /etc/sockd.conf'
        sudo sh -c 'echo "method: username" >> /etc/sockd.conf'
        sudo sh -c 'echo "user.privileged: root" >> /etc/sockd.conf'
        sudo sh -c 'echo "user.unprivileged: nobody" >> /etc/sockd.conf'
        sudo sh -c 'echo "user.libwrap: nobody" >> /etc/sockd.conf'
        sudo sh -c 'echo "client pass {" >> /etc/sockd.conf'
        sudo sh -c 'echo "from: 0.0.0.0/0 to: 0.0.0.0/0" >> /etc/sockd.conf'
        sudo sh -c 'echo "log: connect disconnect error" >> /etc/sockd.conf'
        sudo sh -c 'echo "}" >> /etc/sockd.conf'
        sudo sh -c 'echo "socks pass {" >> /etc/sockd.conf'
        sudo sh -c 'echo "from: 0.0.0.0/0 to: 0.0.0.0/0" >> /etc/sockd.conf'
        sudo sh -c 'echo "log: connect disconnect error" >> /etc/sockd.conf'
        sudo sh -c 'echo "}" >> /etc/sockd.conf'
        sudo service sockd restart
      env:
        SOCKS_USERNAME: ${{ secrets.SOCKS_USERNAME }}
        SOCKS_PASSWORD: ${{ secrets.SOCKS_PASSWORD }}

    - name: Test SOCKS5 connection
      env:
        http_proxy: socks5h://localhost:1080
        https_proxy: socks5h://localhost:1080
      run: |
        curl -s https://api.ipify.org/

    - name: Generate prefixes
      run: |
        python generate_prefixes.py
        echo "#Extended IPv4" >> asn13335.txt
        curl -sSL https://www.cloudflare.com/ips-v4 >> asn13335.txt
        echo "" >> asn13335.txt
        echo "#Extended IPv6" >> asn13335.txt
        curl -sSL https://www.cloudflare.com/ips-v6 >> asn13335.txt
        perl -i -lne 'print unless $seen{$_}++' asn13335.txt
      env:
        http_proxy: http://localhost:3128
        https_proxy: http://localhost:3128

    - name: Generate ufw rules
      run: python generate_ufw.py

# Commit changed files to your repo
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        # Commit message
        commit_message: automatic/regular prefixes updates
        # File pattern used for `git add`. For example `src/*.js`
        file_pattern: ./*.txt
