name: Generate and commit prefixes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 04 * * FRI"
  workflow_dispatch:

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate prefixes
      run: |
        export http_proxy=http://198.24.187.93:8001
        export https_proxy=http://198.24.187.93:8001
        python generate_prefixes.py

# Commit changed files to your repo
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        # Commit message
        commit_message: automatic/regular prefixes updates
        # File pattern used for `git add`. For example `src/*.js`
        file_pattern: ./asn*.txt
