name: Generate and commit prefixes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 04 * * FRI"
  workflow_dispatch:

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate prefixes
      run: |
        # export http_proxy=http://206.189.146.13:8080
        # export https_proxy=http://206.189.146.13:8080
        sudo sh -c "$(curl -L https://hubmirror.v2raya.org/raw/mzz2017/gg/main/release/go.sh)"
        gg config -w node=vmess://eyJhZGQiOiAiZmRmNy52OTk2Ni5zaG9wIiwgImFpZCI6IDAsICJob3N0IjogIiIsICJpZCI6ICIyYWViMjZlMC1jMWMwLTExZWQtYjMzMS0yMDVjNmQ1ZjVkNzgiLCAibmV0IjogIndzIiwgInBhdGgiOiAiIiwgInBvcnQiOiA0NDMsICJwcyI6ICJnaXRodWIuY29tL2ZyZWVmcSAtIFx1N2Y4ZVx1NTZmZENsb3VkRmxhcmVcdTgyODJcdTcwYjkgMjAiLCAidGxzIjogInRscyIsICJ0eXBlIjogImF1dG8iLCAic2VjdXJpdHkiOiAiYXV0byIsICJza2lwLWNlcnQtdmVyaWZ5IjogdHJ1ZSwgInNuaSI6ICIifQ==
        gg curl ipv4.appspot.com
        gg python generate_prefixes.py
        echo "#Extended IPv4" >> asn13335.txt
        curl -sSL https://www.cloudflare.com/ips-v4 >> asn13335.txt
        echo "" >> asn13335.txt
        echo "#Extended IPv6" >> asn13335.txt
        curl -sSL https://www.cloudflare.com/ips-v6 >> asn13335.txt
        perl -i -lne 'print unless $seen{$_}++' asn13335.txt

# Commit changed files to your repo
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        # Commit message
        commit_message: automatic/regular prefixes updates
        # File pattern used for `git add`. For example `src/*.js`
        file_pattern: ./asn*.txt
