name: Generate and commit prefixes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 04 * * FRI"
  workflow_dispatch:

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Privoxy and SOCKS5 proxy
      env:
        USER: ${{ secrets.SOCKS_USERNAME }}
        PASS: ${{ secrets.SOCKS_PASSWORD }}
      run: |
        sudo apt-get update
        sudo apt-get install -y privoxy
        sudo sh -c 'echo "forward-socks5 / ${{ secrets.SOCKS_ADDRESS }}:${{ secrets.SOCKS_PORT }} ." >> /etc/privoxy/config'
        sudo sh -c 'echo "forward-socks5t / ${{ secrets.SOCKS_ADDRESS }}:${{ secrets.SOCKS_PORT }} ." >> /etc/privoxy/config'
        sudo sh -c 'echo "auth-mETHOD \"$USER:$PASS\"" >> /etc/privoxy/config'
        sudo service privoxy restart

    - name: Test SOCKS5 connection
      env:
        http_proxy: http://127.0.0.1:8118
        https_proxy: http://127.0.0.1:8118
      run: |
        curl -s --socks5-hostname ${{ secrets.SOCKS_ADDRESS }}:${{ secrets.SOCKS_PORT }} https://api.ipify.org/

    - name: Generate prefixes
      run: |
        python generate_prefixes.py
        echo "#Extended IPv4" >> asn13335.txt
        curl -sSL https://www.cloudflare.com/ips-v4 >> asn13335.txt
        echo "" >> asn13335.txt
        echo "#Extended IPv6" >> asn13335.txt
        curl -sSL https://www.cloudflare.com/ips-v6 >> asn13335.txt
        perl -i -lne 'print unless $seen{$_}++' asn13335.txt

    - name: Generate ufw rules
      run: python generate_ufw.py

# Commit changed files to your repo
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        # Commit message
        commit_message: automatic/regular prefixes updates
        # File pattern used for `git add`. For example `src/*.js`
        file_pattern: ./*.txt
