name: Generate and commit prefixes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "20 04 * * FRI"
  workflow_dispatch:

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Setup sing-box"
      env:
        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.13.4/sing-box_1.13.4_linux_amd64.deb"
      run: |
          set -Eeuo pipefail
          wget -O sing-box.deb $SING_BOX_DEB_URL
          sudo dpkg -i sing-box.deb

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate prefixes
      env:
        IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
      run: |
        python generate_prefixes.py

    - name: Deploy to release branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: release
        publish_dir: ./build
        keep_files: false
